version: '3.7'

services:
  android-container:
    image: budtmo/docker-android:emulator_11.0
    container_name: android-container
    privileged: true
    environment:
      - EMULATOR_DEVICE=Samsung Galaxy S10
      - WEB_VNC=true
      - APPIUM=true                        # Start Appium server
    volumes:
      - ./:/code                      # Mount current folder into container as /code
      - data:/home/androidusr
      - root:/root
    working_dir: /code                    # Set working directory to /code
    ports:
      - "6080:6080"                       # VNC Web UI
      - "4723:4723"                       # Appium server port
    devices:
      - "/dev/kvm:/dev/kvm"
    restart: always

volumes:
  data:
  root:
